// GuessImageData_3.js — الفئات: شخصيات أفلام، سيارات، شخصيات ألعاب
// + GUESS_CATEGORIES + pickRandomImage
// الجزء الثالث من ثلاثة أجزاء

export const GUESS_IMAGE_DATA_3 = {

  // ══════════════════════════════════════════════
  //  FILM_CHARS — شخصيات أفلام (50)
  // ══════════════════════════════════════════════
  "film_chars": [
    { "id": "fc01", "answer": "آيرون مان", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/8/8a/Ironman_2008.jpg/400px-Ironman_2008.jpg", "info": { "الكون": "Marvel MCU", "الممثل": "روبرت داوني جونيور", "الاسم الحقيقي": "طوني ستارك", "الأفلام": "ظهر في 10 أفلام MCU", "الإنجاز": "مؤسس فريق أفنجرز" } },
    { "id": "fc02", "answer": "باتمان", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/The_Dark_Knight_%282008_film%29.jpg/400px-The_Dark_Knight_%282008_film%29.jpg", "info": { "الكون": "DC Comics", "الممثل الأشهر": "كريستيان بيل في The Dark Knight", "الاسم الحقيقي": "بروس واين", "القوة": "لا قوى خارقة — يعتمد على الذكاء والتدريب والثروة" } },
    { "id": "fc03", "answer": "سيمبا", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/1/1e/The_Lion_King_poster.jpg/400px-The_Lion_King_poster.jpg", "info": { "الكون": "Disney — The Lion King 1994", "النوع": "رسوم متحركة", "الصوت": "جوناثان تايلر توماس (صغير)، ماتيو برودريك (كبير)", "الإلهام": "مستوحى من هاملت لشكسبير" } },
    { "id": "fc04", "answer": "جوكر", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/Joker_%282019_film%29_poster.jpg/400px-Joker_%282019_film%29_poster.jpg", "info": { "الكون": "DC Comics", "الممثل الأشهر": "واكين فينيكس (2019)، هيث ليدجر (2008)", "الاسم الحقيقي": "آرثر فليك / غير محدد", "اللقب": "أيقوني من أعظم شخصيات الشرير في التاريخ" } },
    { "id": "fc05", "answer": "سبايدرمان", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/Spider-Man_%28film%29_poster.jpg/400px-Spider-Man_%28film%29_poster.jpg", "info": { "الكون": "Marvel Comics", "الممثلون": "توبي ماغواير، أندرو غارفيلد، توم هولاند", "الاسم الحقيقي": "بيتر باركر", "القوة": "شبكة العنكبوت، حاسة العنكبوت، القوة الخارقة" } },
    { "id": "fc06", "answer": "ثانوس", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d9/Avengers_Infinity_War_poster.jpg/400px-Avengers_Infinity_War_poster.jpg", "info": { "الكون": "Marvel MCU", "الممثل": "جوش برولين", "الهدف": "محو نصف الكون لـ'إنقاذ الموارد'", "الأداة": "قفاز اللانهاية بـ6 جواهر" } },
    { "id": "fc07", "answer": "كابتن أمريكا", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/3/37/Captain_America_The_First_Avenger_poster.jpg/400px-Captain_America_The_First_Avenger_poster.jpg", "info": { "الكون": "Marvel MCU", "الممثل": "كريس إيفانز", "الاسم الحقيقي": "ستيف روجرز", "الدرع": "مصنوعة من Vibranium — تمتص الطاقة" } },
    { "id": "fc08", "answer": "ثور", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/b/b0/Thor_%28film%29_poster.jpg/400px-Thor_%28film%29_poster.jpg", "info": { "الكون": "Marvel MCU / الأساطير الإسكندنافية", "الممثل": "كريس هيمسورث", "السلاح": "مطرقة Mjolnir — لا يحملها إلا الجدير", "المهمة": "إله الرعد ابن أودين" } },
    { "id": "fc09", "answer": "هالك", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/c/c8/The_Avengers_%282012_film%29_poster.jpg/400px-The_Avengers_%282012_film%29_poster.jpg", "info": { "الكون": "Marvel MCU", "الممثل": "مارك روفالو (MCU)", "الاسم الحقيقي": "دكتور بروس بانر", "القوة": "كلما زاد الغضب زادت القوة — لا حد أقصى" } },
    { "id": "fc10", "answer": "نيمو", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/c/ca/Finding_Nemo.jpg/400px-Finding_Nemo.jpg", "info": { "الكون": "Pixar — Finding Nemo 2003", "النوع": "سمكة أبو شراع (Clownfish)", "القصة": "والده يعبر المحيط للبحث عنه بعد اختطافه", "الجوائز": "أوسكار أفضل فيلم رسوم متحرك 2004" } },
    { "id": "fc11", "answer": "دوري", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Finding_Dory_%282016_film%29_poster.jpg/400px-Finding_Dory_%282016_film%29_poster.jpg", "info": { "الكون": "Pixar — Finding Dory 2016", "النوع": "سمكة ذيل الدرّاج الزرقاء", "الميزة": "تعاني من فقدان الذاكرة القصيرة المدى", "المرفق": "الجزء الثاني من Finding Nemo" } },
    { "id": "fc12", "answer": "ودي", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Woody_Toy_Story_character.png/400px-Woody_Toy_Story_character.png", "info": { "الكون": "Pixar — Toy Story 1995", "النوع": "دمية رعاة بقر", "الصوت": "توم هانكس", "الشخصية": "قائد مجموعة الألعاب — يقدّم الولاء للطفل أنيدي" } },
    { "id": "fc13", "answer": "باز لايتيار", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/7/71/Buzz_Lightyear_ToyStory.PNG/400px-Buzz_Lightyear_ToyStory.PNG", "info": { "الكون": "Pixar — Toy Story 1995", "النوع": "دمية رائد فضاء", "الصوت": "تيم ألن", "الشعار": "إلى ما لا نهاية وما هو أبعد" } },
    { "id": "fc14", "answer": "جاك سبارو", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/5/52/Pirates-of-the-caribbean-curse-of-the-black-pearl.jpg/400px-Pirates-of-the-caribbean-curse-of-the-black-pearl.jpg", "info": { "الكون": "Pirates of the Caribbean", "الممثل": "جوني ديب", "المركب": "Black Pearl", "الشخصية": "قرصان غير قابل للتنبؤ بذكاء خفي" } },
    { "id": "fc15", "answer": "غانداف", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/e/e1/Gandalf600ppx.jpg/400px-Gandalf600ppx.jpg", "info": { "الكون": "The Lord of the Rings — تولكين", "الممثل": "إيان ماكيلن", "اللقب": "غانداف الرمادي ثم غانداف الأبيض", "الأشهر": "You shall not pass!" } },
    { "id": "fc16", "answer": "فرودو", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Frodo_bag.jpg/400px-Frodo_bag.jpg", "info": { "الكون": "The Lord of the Rings — تولكين", "الممثل": "إيليجا وود", "المهمة": "تدمير خاتم القوة في براكين مورودور", "الأصل": "هوبيت — كائن صغير قريب من البشر" } },
    { "id": "fc17", "answer": "داث فيدر", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Star_Wars_The_Force_Awakens_Theatrical_Poster.jpg/400px-Star_Wars_The_Force_Awakens_Theatrical_Poster.jpg", "info": { "الكون": "Star Wars", "الممثل": "ديفيد بروز / صوت جيمس إيرل جونز", "الاسم الحقيقي": "أناكن سكاي ووكر", "الأشهر": "I am your father — الأشهر في تاريخ السينما" } },
    { "id": "fc18", "answer": "يودا", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Yoda_SWSB.png/400px-Yoda_SWSB.png", "info": { "الكون": "Star Wars", "العمر": "900 سنة عند وفاته", "الشخصية": "أعظم أسياد القوة — يتكلم بترتيب مقلوب", "الأشهر": "Do or do not, there is no try" } },
    { "id": "fc19", "answer": "هاري بوتر", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/d/db/Harry_Potter_%26_the_Deathly_Hallows_P2.jpg/400px-Harry_Potter_%26_the_Deathly_Hallows_P2.jpg", "info": { "الكون": "Harry Potter — ج.ك رولينج", "الممثل": "دانيال ريدكليف", "المدرسة": "هوغوورتس — بيت غريفيندور", "العصا": "هولي وريشة عنقاء — توأم عصا فولدمورت" } },
    { "id": "fc20", "answer": "هرميون غرينجر", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Hermione_Granger_poster.jpg/400px-Hermione_Granger_poster.jpg", "info": { "الكون": "Harry Potter — ج.ك رولينج", "الممثلة": "إيما واتسون", "الشخصية": "الأذكى في هوغوورتس — بيت غريفيندور", "الأشهر": "It's leviOsa not levioSA" } },
    { "id": "fc21", "answer": "شريك", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Shrek_character.png/400px-Shrek_character.png", "info": { "الكون": "DreamWorks — Shrek 2001", "النوع": "غول أخضر ضخم", "الصوت": "مايك مايرز", "الشخصية": "يعيش في المستنقع وحيداً — قصة ساخرة على أساطير الأميرات" } },
    { "id": "fc22", "answer": "علاء الدين", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/2/21/Aladdin_%281992_film%29_poster.jpg/400px-Aladdin_%281992_film%29_poster.jpg", "info": { "الكون": "Disney — Aladdin 1992", "الأصل": "ألف ليلة وليلة", "الصوت": "سكوت ويينغر", "العنصر الأشهر": "المارد والمصباح السحري" } },
    { "id": "fc23", "answer": "الجني", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Genie_Aladdin.png/400px-Genie_Aladdin.png", "info": { "الكون": "Disney — Aladdin 1992", "الصوت": "روبن ويليامز (المبدع)، ويل سميث (2019)", "القوة": "يمنح 3 أمنيات لمن يجد المصباح", "القيد": "لا يستطيع إحياء الموتى أو إجبار شخص على الحب" } },
    { "id": "fc24", "answer": "ترزان", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cb/Tarzan_Disney_poster.jpg/400px-Tarzan_Disney_poster.jpg", "info": { "الكون": "Disney — Tarzan 1999", "الأصل": "رواية إدغار رايس باروز 1912", "القصة": "طفل إنجليزي تربيّه القردة في أدغال أفريقيا", "الجوائز": "أوسكار أفضل موسيقى لفيل كولينز" } },
    { "id": "fc25", "answer": "بياض الثلج", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/7/74/Snow_White_%281937%29_poster.jpg/400px-Snow_White_%281937%29_poster.jpg", "info": { "الكون": "Disney — Snow White 1937", "التميز": "أول فيلم رسوم متحركة بطول كامل في تاريخ السينما", "الأشهر": "المرآة المرآة على الحائط" } },
    { "id": "fc26", "answer": "سندريلا", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/6/69/Cinderella_%281950_film%29_poster.jpg/400px-Cinderella_%281950_film%29_poster.jpg", "info": { "الكون": "Disney — Cinderella 1950", "الأصل": "خرافة شارل بيرو 1697", "الأشهر": "حذاء الزجاج والقرع الذي تحوّل لعربة" } },
    { "id": "fc27", "answer": "إلسا", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Frozen_%282013_film%29_poster.jpg/400px-Frozen_%282013_film%29_poster.jpg", "info": { "الكون": "Disney — Frozen 2013", "الصوت": "إيدينا مينزل", "القوة": "التحكم في الجليد والثلج", "أشهر أغنية": "Let It Go — فازت بأوسكار أفضل أغنية" } },
    { "id": "fc28", "answer": "بيل (الجميلة)", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/5/52/Beauty_and_the_Beast_%282017_film%29_poster.jpg/400px-Beauty_and_the_Beast_%282017_film%29_poster.jpg", "info": { "الكون": "Disney — Beauty and the Beast", "الممثلة (2017)": "إيما واتسون", "الشخصية": "أميرة مثقفة تحب القراءة — لا تحكم بالمظهر", "الرسالة": "الجمال الحقيقي في الداخل" } },
    { "id": "fc29", "answer": "ميغيل (كوكو)", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/5/58/Coco_%282017_film%29_poster.jpg/400px-Coco_%282017_film%29_poster.jpg", "info": { "الكون": "Pixar — Coco 2017", "الجنسية": "مكسيكي", "القصة": "يسافر لعالم الأموات أثناء عيد الموتى", "الجوائز": "أوسكار أفضل فيلم رسوم متحرك وأفضل أغنية" } },
    { "id": "fc30", "answer": "سانتا إيكسبيريتو", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Coco_Movie_Skull.jpg/400px-Coco_Movie_Skull.jpg", "info": { "الكون": "Pixar — Coco 2017", "الطابع": "شخصية تجسّد ذكريات المتوفين في عالم الأموات", "الثقافة": "مستوحى من تقاليد عيد الموتى المكسيكي" } },
    { "id": "fc31", "answer": "وول-إي", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/1/1b/WALL-E_2008_film_poster.jpg/400px-WALL-E_2008_film_poster.jpg", "info": { "الكون": "Pixar — WALL-E 2008", "الجوائز": "أوسكار أفضل فيلم رسوم متحرك 2009", "الرسالة": "قصة حب بين روبوتين في كوكب مدمر بالنفايات", "الحوار": "أقل فيلم حوار في تاريخ Pixar" } },
    { "id": "fc32", "answer": "ماكوين (سيارات)", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/5/52/Cars_%282006_film%29_poster.jpg/400px-Cars_%282006_film%29_poster.jpg", "info": { "الكون": "Pixar — Cars 2006", "الشخصية": "سيارة سباق حمراء — Lightning McQueen", "الصوت": "أوين ويلسون", "الشعار": "Ka-chow!" } },
    { "id": "fc33", "answer": "ريمي (رتاتوي)", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Ratatouille_%28film%29_poster.jpg/400px-Ratatouille_%28film%29_poster.jpg", "info": { "الكون": "Pixar — Ratatouille 2007", "الشخصية": "فأر يحلم بأن يصبح طاهياً في مطعم باريسي", "الجوائز": "أوسكار أفضل فيلم رسوم متحرك 2008", "الشعار": "أي شخص يستطيع الطهي" } },
    { "id": "fc34", "answer": "دمبو", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a8/Dumbo_%282019_film%29_poster.jpg/400px-Dumbo_%282019_film%29_poster.jpg", "info": { "الكون": "Disney — Dumbo", "الميزة": "فيل صغير بأذنين ضخمتين يمكنّانه من الطيران", "الرسالة": "ما يجعلك مختلفاً قد يكون أعظم نقاط قوتك" } },
    { "id": "fc35", "answer": "موانا", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/b/b0/Moana_teaser_poster.jpg/400px-Moana_teaser_poster.jpg", "info": { "الكون": "Disney — Moana 2016", "الأصل": "مستوحى من أساطير المحيط الهادئ البولينيزية", "الصوت": "أولي فاليولو", "الجوائز": "غولدن غلوب أفضل فيلم رسوم متحرك" } },
    { "id": "fc36", "answer": "ميرايدا", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/d/da/Brave_Poster.jpg/400px-Brave_Poster.jpg", "info": { "الكون": "Pixar — Brave 2012", "الجنسية": "اسكتلندية", "الميزة": "أميرة تقاوم الزواج المرتب وتريد رسم مصيرها", "الجوائز": "أوسكار أفضل فيلم رسوم متحرك 2013" } },
    { "id": "fc37", "answer": "رابنزل", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/3/31/Tangled_poster.jpg/400px-Tangled_poster.jpg", "info": { "الكون": "Disney — Tangled 2010", "الأصل": "خرافة رابنزل الألمانية", "الميزة": "شعرها الطويل السحري يشفي الجروح", "الجوائز": "أوسكار ترشيح لأفضل أغنية" } },
    { "id": "fc38", "answer": "بامبي", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/b/b3/Bambi_%281942_film%29_poster.jpg/400px-Bambi_%281942_film%29_poster.jpg", "info": { "الكون": "Disney — Bambi 1942", "الأصل": "رواية فيليكس سالتن 1923", "الشخصية": "غزال صغير يفقد أمه على يد الصيادين", "التأثير": "أثّر في وعي جيل كامل بشأن حماية البيئة" } },
    { "id": "fc39", "answer": "بينوكيو", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/0/0a/Pinocchio_%281940%29_poster.jpg/400px-Pinocchio_%281940%29_poster.jpg", "info": { "الكون": "Disney — Pinocchio 1940", "الأصل": "قصة كارلو كولودي الإيطالية 1883", "الأشهر": "أنفه يطول عند الكذب", "الجوائز": "أوسكاران للموسيقى والأغنية" } },
    { "id": "fc40", "answer": "النملة (أنت-مان)", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/e/e2/Ant-Man_and_the_Wasp_film_poster.jpg/400px-Ant-Man_and_the_Wasp_film_poster.jpg", "info": { "الكون": "Marvel MCU", "الممثل": "بول رود", "الاسم الحقيقي": "سكوت لانغ", "القوة": "يتقلص لحجم نملة مع الاحتفاظ بقوته الكاملة" } },
    { "id": "fc41", "answer": "دكتور سترينج", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/2/2c/Doctor_Strange_poster.jpg/400px-Doctor_Strange_poster.jpg", "info": { "الكون": "Marvel MCU", "الممثل": "بنيديكت كامبيرباتش", "الاسم الحقيقي": "دكتور ستيفن سترينج", "القوة": "سيد الفنون السحرية — يتحكم في الزمن" } },
    { "id": "fc42", "answer": "بلاك بانثر", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Black_Panther_film_poster.jpg/400px-Black_Panther_film_poster.jpg", "info": { "الكون": "Marvel MCU", "الممثل": "تشادويك بوسمان (توفي 2020)", "الاسم الحقيقي": "تيتشالا", "الوطن": "واكاندا — دولة أفريقية خيالية بتكنولوجيا متقدمة" } },
    { "id": "fc43", "answer": "واندا ماكسيموف", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/WandaVision_logo.jpg/400px-WandaVision_logo.jpg", "info": { "الكون": "Marvel MCU", "الممثلة": "إليزابيث أولسن", "اللقب": "Scarlet Witch", "القوة": "التحكم في الواقع والتخاطر" } },
    { "id": "fc44", "answer": "غروت", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/4/49/Guardians_of_the_Galaxy_%282014_film%29_poster.jpg/400px-Guardians_of_the_Galaxy_%282014_film%29_poster.jpg", "info": { "الكون": "Marvel MCU — Guardians of the Galaxy", "الممثل (صوت)": "فين ديزل", "الحوار الكامل": "I am Groot — كل جمله هذه الجملة فقط", "التميز": "شخصية تجسّد الحب والتضحية بكلمات بسيطة" } },
    { "id": "fc45", "answer": "راكون (روكيت)", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Rocket_Raccoon.png/400px-Rocket_Raccoon.png", "info": { "الكون": "Marvel MCU — Guardians of the Galaxy", "الصوت": "برادلي كوبر", "الشخصية": "راكون معدّل جينياً خبير بالأسلحة", "العلاقة": "أفضل أصدقاء مع غروت" } },
    { "id": "fc46", "answer": "سوبرمان", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d9/Batman_v_Superman_poster.jpg/400px-Batman_v_Superman_poster.jpg", "info": { "الكون": "DC Comics", "الممثل الأشهر": "هنري كافيل، كريستوفر ريف", "الاسم الحقيقي": "كلارك كينت / كال-إل", "القوة": "الطيران، الليزر من العيون، القوة الخارقة، الحصانة" } },
    { "id": "fc47", "answer": "وندر وومان", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Wonder_Woman_2017_film.jpg/400px-Wonder_Woman_2017_film.jpg", "info": { "الكون": "DC Comics", "الممثلة": "غال غادوت", "الاسم الحقيقي": "ديانا — أميرة الأمازون", "الأداة": "سوط الحقيقة — يجبر من تُلقى عليه على قول الحقيقة" } },
    { "id": "fc48", "answer": "أكوامان", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Aquaman_%28film%29_poster.jpg/400px-Aquaman_%28film%29_poster.jpg", "info": { "الكون": "DC Comics", "الممثل": "جيسون موموا", "الاسم الحقيقي": "آرثر كاري", "القوة": "التكلم مع الكائنات البحرية والقتال تحت الماء" } },
    { "id": "fc49", "answer": "فلاش", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/5/53/The_Flash_%28film%29_poster.jpg/400px-The_Flash_%28film%29_poster.jpg", "info": { "الكون": "DC Comics", "الممثل": "إيزرا ميلر", "الاسم الحقيقي": "باري ألن", "القوة": "الأسرع في الكون — يتحرك بسرعة تفوق الضوء" } },
    { "id": "fc50", "answer": "سايكلوبس", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d4/X-Men_%28film%29_poster.jpg/400px-X-Men_%28film%29_poster.jpg", "info": { "الكون": "Marvel — X-Men", "الممثل": "جيمس مارسدن", "الاسم الحقيقي": "سكوت سامرز", "القوة": "يطلق حزمة طاقة من عينيه — يرتدي نظارة خاصة للتحكم" } }
  ],

  // ══════════════════════════════════════════════
  //  CARS — سيارات (50)
  // ══════════════════════════════════════════════
  "cars": [
    { "id": "ca01", "answer": "فيراري 488 GTB", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/2019_Ferrari_488_GTB.jpg/400px-2019_Ferrari_488_GTB.jpg", "info": { "الشركة": "Ferrari — إيطاليا", "السنة": "2015", "المحرك": "V8 توربو 3.9L", "القوة": "660 حصان", "أقصى سرعة": "330 كم/س" } },
    { "id": "ca02", "answer": "لامبورغيني هوراكان", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/2018_Lamborghini_Hurac%C3%A1n_Perf.jpg/400px-2018_Lamborghini_Hurac%C3%A1n_Perf.jpg", "info": { "الشركة": "Lamborghini — إيطاليا", "السنة": "2014", "المحرك": "V10 طبيعي 5.2L", "القوة": "610 حصان", "أقصى سرعة": "325 كم/س" } },
    { "id": "ca03", "answer": "بورشه 911", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Porsche_boxster_986.jpg/400px-Porsche_boxster_986.jpg", "info": { "الشركة": "Porsche — ألمانيا", "السنة": "1963 — الآن", "المحرك": "Flat-6 توربو", "القوة": "385-650 حصان حسب الإصدار", "التميز": "المحرك في الخلف — تصميم لا مثيل له" } },
    { "id": "ca04", "answer": "فورد موستانج", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Ford_Mustang_2018_003.jpg/400px-Ford_Mustang_2018_003.jpg", "info": { "الشركة": "Ford — الولايات المتحدة", "السنة": "1964 — الآن", "المحرك": "V8 5.0L Coyote", "القوة": "450 حصان", "التميز": "أيقونة الـ Muscle Car الأمريكية" } },
    { "id": "ca05", "answer": "بوغاتي شيرون", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Bugatti_Chiron_2019_cropped.jpg/400px-Bugatti_Chiron_2019_cropped.jpg", "info": { "الشركة": "Bugatti — فرنسا", "السنة": "2016", "المحرك": "W16 توربو مزدوج 8.0L", "القوة": "1500 حصان", "أقصى سرعة": "420 كم/س — الأسرع إنتاجاً" } },
    { "id": "ca06", "answer": "مرسيدس AMG GT R", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Mercedes-AMG_GT_R_%28cropped%29.jpg/400px-Mercedes-AMG_GT_R_%28cropped%29.jpg", "info": { "الشركة": "Mercedes-AMG — ألمانيا", "السنة": "2016", "المحرك": "V8 بيتوربو 4.0L", "القوة": "577 حصان", "اللقب": "وحش النوربيرغرينغ" } },
    { "id": "ca07", "answer": "BMW M3", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/BMW_M3_E46_-_front_%28cropped%29.jpg/400px-BMW_M3_E46_-_front_%28cropped%29.jpg", "info": { "الشركة": "BMW — ألمانيا", "السنة": "1986 — الآن", "المحرك": "I6 توربو 3.0L (الجيل الحالي)", "القوة": "503 حصان", "التميز": "الأفضل في قيادة سيارات السيدان الرياضية" } },
    { "id": "ca08", "answer": "أودي R8", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/2013_Audi_R8_V10_FSI_%28cropped%29.jpg/400px-2013_Audi_R8_V10_FSI_%28cropped%29.jpg", "info": { "الشركة": "Audi — ألمانيا", "السنة": "2006 — الآن", "المحرك": "V10 طبيعي 5.2L", "القوة": "610 حصان", "التميز": "الوحيدة من فئتها بمحرك V10 طبيعي" } },
    { "id": "ca09", "answer": "رولز رويس غوست", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/2021_Rolls-Royce_Ghost_%28UK%2C_facelift%29_front.jpg/400px-2021_Rolls-Royce_Ghost_%28UK%2C_facelift%29_front.jpg", "info": { "الشركة": "Rolls-Royce — المملكة المتحدة", "السنة": "2009 — الآن", "المحرك": "V12 بيتوربو 6.75L", "القوة": "563 حصان", "التميز": "الهدوء المطلق — معزول صوتياً بالكامل" } },
    { "id": "ca10", "answer": "بنتلي كونتيننتال GT", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/2018_Bentley_Continental_GT_W12_First_Edition.jpg/400px-2018_Bentley_Continental_GT_W12_First_Edition.jpg", "info": { "الشركة": "Bentley — المملكة المتحدة", "السنة": "2003 — الآن", "المحرك": "W12 توربو 6.0L", "القوة": "626 حصان", "التميز": "جمع الفخامة مع الأداء الرياضي" } },
    { "id": "ca11", "answer": "ماكلارين 720S", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/McLaren_720S_coupe%2C_front_8.3.18.jpg/400px-McLaren_720S_coupe%2C_front_8.3.18.jpg", "info": { "الشركة": "McLaren — المملكة المتحدة", "السنة": "2017", "المحرك": "V8 بيتوربو 4.0L", "القوة": "710 حصان", "أقصى سرعة": "341 كم/س" } },
    { "id": "ca12", "answer": "فيراري F40", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Ferrari_F40%2C_Mugello_Circuit%2C_Italy.jpg/400px-Ferrari_F40%2C_Mugello_Circuit%2C_Italy.jpg", "info": { "الشركة": "Ferrari — إيطاليا", "السنة": "1987-1992", "المحرك": "V8 بيتوربو 2.9L", "القوة": "478 حصان", "التميز": "آخر سيارة وافق عليها إنزو فيراري شخصياً" } },
    { "id": "ca13", "answer": "دودج تشالنجر SRT", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/2015_Dodge_Challenger_R%2FT_-_front.jpg/400px-2015_Dodge_Challenger_R%2FT_-_front.jpg", "info": { "الشركة": "Dodge — الولايات المتحدة", "السنة": "1970 (الأصل) — 2008 الإحياء", "المحرك": "V8 HEMI 6.2L Hellcat", "القوة": "717 حصان", "التميز": "أقوى muscle car أمريكية إنتاجية" } },
    { "id": "ca14", "answer": "تسلا موديل S", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/2020_Tesla_Model_S_Long_Range_Plus%2C_front.jpg/400px-2020_Tesla_Model_S_Long_Range_Plus%2C_front.jpg", "info": { "الشركة": "Tesla — الولايات المتحدة", "السنة": "2012 — الآن", "المحرك": "كهربائي كامل", "القوة": "1020 حصان (Plaid)", "التميز": "0-100 في 1.99 ثانية — أسرع سيارة إنتاجية" } },
    { "id": "ca15", "answer": "نيسان GT-R", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/2013_Nissan_GT-R_%28R35%29%2C_front_5.7.18.jpg/400px-2013_Nissan_GT-R_%28R35%29%2C_front_5.7.18.jpg", "info": { "الشركة": "Nissan — اليابان", "السنة": "2007 — الآن", "المحرك": "V6 بيتوربو 3.8L VR38DETT", "القوة": "565 حصان", "اللقب": "Godzilla — أداء سوبركار بنصف السعر" } },
    { "id": "ca16", "answer": "تويوتا GR سوبرا", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/2019_Toyota_GR_Supra_A90%2C_front_8.16.19.jpg/400px-2019_Toyota_GR_Supra_A90%2C_front_8.16.19.jpg", "info": { "الشركة": "Toyota — اليابان", "السنة": "2019 (الإحياء)", "المحرك": "I6 توربو B58 3.0L (BMW)", "القوة": "382 حصان", "التميز": "أيقونة الثقافة اليابانية للسيارات وعالم JDM" } },
    { "id": "ca17", "answer": "شيفروليه كورفيت", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/2020_Chevrolet_Corvette_Stingray%2C_front.jpg/400px-2020_Chevrolet_Corvette_Stingray%2C_front.jpg", "info": { "الشركة": "Chevrolet — الولايات المتحدة", "السنة": "1953 — الآن", "المحرك": "V8 LT2 6.2L (C8)", "القوة": "495 حصان", "التميز": "أمريكا الوحيدة المنافسة لسوبركارات أوروبية بنصف السعر" } },
    { "id": "ca18", "answer": "مازيراتي جيبلي", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/2016_Maserati_Ghibli_S_Q4_%28UK%29%2C_front.jpg/400px-2016_Maserati_Ghibli_S_Q4_%28UK%29%2C_front.jpg", "info": { "الشركة": "Maserati — إيطاليا", "السنة": "2013 — الآن", "المحرك": "V6 بيتوربو 3.0L", "القوة": "345-430 حصان", "التميز": "الصوت الموسيقي المميز للعادم الإيطالي" } },
    { "id": "ca19", "answer": "ألفا روميو 4C", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Alfa_Romeo_4C_%28cropped%29.jpg/400px-Alfa_Romeo_4C_%28cropped%29.jpg", "info": { "الشركة": "Alfa Romeo — إيطاليا", "السنة": "2013-2020", "المحرك": "I4 توربو 1.75L", "القوة": "240 حصان", "التميز": "هيكل كربون خفيف — تجربة قيادة نقية بلا مساعدات" } },
    { "id": "ca20", "answer": "رينج روفر", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Range_Rover_2013_%28cropped%29.jpg/400px-Range_Rover_2013_%28cropped%29.jpg", "info": { "الشركة": "Land Rover — المملكة المتحدة", "السنة": "1970 — الآن", "المحرك": "V8 سوبرتشارجر 5.0L", "القوة": "565 حصان", "التميز": "ملك الـ SUV الفاخرة عالمياً" } },
    { "id": "ca21", "answer": "مرسيدس G-Class", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Mercedes-Benz_G_350d%2C_2020_%28cropped%29.jpg/400px-Mercedes-Benz_G_350d%2C_2020_%28cropped%29.jpg", "info": { "الشركة": "Mercedes-Benz — ألمانيا", "السنة": "1979 — الآن", "المحرك": "V8 بيتوربو 4.0L (AMG G63)", "القوة": "577 حصان", "التميز": "تصميم مكعب لم يتغير منذ 1979 — أيقونة الترف والتضاريس" } },
    { "id": "ca22", "answer": "لكزس LFA", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Lexus_LFA_%28cropped%29.jpg/400px-Lexus_LFA_%28cropped%29.jpg", "info": { "الشركة": "Lexus — اليابان", "السنة": "2010-2012", "المحرك": "V10 طبيعي 4.8L (يابان F1)", "القوة": "552 حصان", "التميز": "صوت المحرك مثل الـ F1 — قيمتها ارتفعت للضعف بعد التوقف" } },
    { "id": "ca23", "answer": "باغاني هوايرا", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Pagani_Huayra_-_Flickr_-_Alexandre_Pr%C3%A9vot.jpg/400px-Pagani_Huayra_-_Flickr_-_Alexandre_Pr%C3%A9vot.jpg", "info": { "الشركة": "Pagani — إيطاليا", "السنة": "2011", "المحرك": "V12 AMG بيتوربو 6.0L", "القوة": "730 حصان", "التميز": "تحفة فنية — كل قطعة مصنوعة يدوياً" } },
    { "id": "ca24", "answer": "فيراري لا فيراري", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Ferrari_LaFerrari_%28cropped%29.jpg/400px-Ferrari_LaFerrari_%28cropped%29.jpg", "info": { "الشركة": "Ferrari — إيطاليا", "السنة": "2013-2016", "المحرك": "V12 هجين 6.3L + موتور كهربائي", "القوة": "963 حصان", "التميز": "499 نسخة فقط — بيع بأكثر من مليوني دولار" } },
    { "id": "ca25", "answer": "لامبورغيني أفنتادور", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Lamborghini_Aventador_LP700-4_%28cropped%29.jpg/400px-Lamborghini_Aventador_LP700-4_%28cropped%29.jpg", "info": { "الشركة": "Lamborghini — إيطاليا", "السنة": "2011-2023", "المحرك": "V12 طبيعي 6.5L", "القوة": "769 حصان", "أقصى سرعة": "350 كم/س" } },
    { "id": "ca26", "answer": "أستون مارتن DB9", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Aston_Martin_DB9_Coupe_%28cropped%29.jpg/400px-Aston_Martin_DB9_Coupe_%28cropped%29.jpg", "info": { "الشركة": "Aston Martin — المملكة المتحدة", "السنة": "2004-2016", "المحرك": "V12 طبيعي 5.9L", "القوة": "510 حصان", "التميز": "سيارة جيمس بوند الأشهر" } },
    { "id": "ca27", "answer": "ماكلارين P1", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/2014_McLaren_P1_-_front.jpg/400px-2014_McLaren_P1_-_front.jpg", "info": { "الشركة": "McLaren — المملكة المتحدة", "السنة": "2013-2015", "المحرك": "V8 هجين بيتوربو 3.8L + موتور كهربائي", "القوة": "916 حصان", "التميز": "جزء من ثالوث الهايبركار مع LaFerrari وPorsche 918" } },
    { "id": "ca28", "answer": "شيفروليه كامارو", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/2016_Chevrolet_Camaro_RS%2C_front_1.9.16.jpg/400px-2016_Chevrolet_Camaro_RS%2C_front_1.9.16.jpg", "info": { "الشركة": "Chevrolet — الولايات المتحدة", "السنة": "1966 — الآن", "المحرك": "V8 LT1 6.2L", "القوة": "455 حصان", "التميز": "المنافس التاريخي للموستانج — سيارة بامبلبي في Transformers" } },
    { "id": "ca29", "answer": "فورد GT", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/2017_Ford_GT_%28cropped%29.jpg/400px-2017_Ford_GT_%28cropped%29.jpg", "info": { "الشركة": "Ford — الولايات المتحدة", "السنة": "2017-2022", "المحرك": "V6 EcoBoost توربو 3.5L", "القوة": "647 حصان", "التميز": "فازت في Le Mans 2016 بذكرى انتصار 1966 على فيراري" } },
    { "id": "ca30", "answer": "ميتسوبيشي لانسر EVO", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/2005_Mitsubishi_Lancer_Evolution_VIII_%28cropped%29.jpg/400px-2005_Mitsubishi_Lancer_Evolution_VIII_%28cropped%29.jpg", "info": { "الشركة": "Mitsubishi — اليابان", "السنة": "1992-2016", "المحرك": "I4 توربو 4G63/4B11", "القوة": "295-405 حصان", "التميز": "العدو التاريخي لـ WRX STI — أيقونة رالي العالم" } },
    { "id": "ca31", "answer": "سوبارو إمبريزا WRX STI", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Subaru_Impreza_WRX_STi_-_Flickr_-_Alexandre_Pr%C3%A9vot.jpg/400px-Subaru_Impreza_WRX_STi_-_Flickr_-_Alexandre_Pr%C3%A9vot.jpg", "info": { "الشركة": "Subaru — اليابان", "السنة": "1992 — الآن", "المحرك": "Flat-4 توربو EJ257/FA24DIT", "القوة": "310 حصان", "التميز": "بطل رالي العالم WRC متعدد المرات" } },
    { "id": "ca32", "answer": "BMW i8", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/BMW_i8_coupe_%28cropped%29.jpg/400px-BMW_i8_coupe_%28cropped%29.jpg", "info": { "الشركة": "BMW — ألمانيا", "السنة": "2014-2020", "المحرك": "I3 توربو هجين + موتور كهربائي", "القوة": "369 حصان", "التميز": "أبواب Scissor مع اقتصاد هجين — سيارة المستقبل" } },
    { "id": "ca33", "answer": "تويوتا لاند كروزر", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/2016_Toyota_Land_Cruiser_200_facelift_%28cropped%29.jpg/400px-2016_Toyota_Land_Cruiser_200_facelift_%28cropped%29.jpg", "info": { "الشركة": "Toyota — اليابان", "السنة": "1951 — الآن", "المحرك": "V8 ديزل 4.5L أو V6 بنزين 4.0L", "التميز": "الأموالة الأكثر موثوقية في التاريخ — الخيار الأول للجيوش والأمم المتحدة" } },
    { "id": "ca34", "answer": "نيسان باترول", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Nissan_Patrol_Y62_%28cropped%29.jpg/400px-Nissan_Patrol_Y62_%28cropped%29.jpg", "info": { "الشركة": "Nissan — اليابان", "السنة": "1951 — الآن", "المحرك": "V8 بنزين 5.6L (Y62)", "القوة": "400 حصان", "التميز": "الملك الخليجي بامتياز — الأكثر مبيعاً في دول الخليج" } },
    { "id": "ca35", "answer": "مرسيدس S-Class", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/2021_Mercedes-Benz_S_500_4MATIC_%28W223%29.jpg/400px-2021_Mercedes-Benz_S_500_4MATIC_%28W223%29.jpg", "info": { "الشركة": "Mercedes-Benz — ألمانيا", "السنة": "1972 — الآن", "المحرك": "I6/V8/V12 توربو", "التميز": "قمة الفخامة — كل تقنية مرسيدس تظهر هنا أولاً" } },
    { "id": "ca36", "answer": "كونيغسيغ", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image-Koenigsegg.jpg/400px-Image-Koenigsegg.jpg", "info": { "الشركة": "Koenigsegg — السويد", "السنة": "2002 — الآن", "أسرع نموذج": "Jesko Absolut — نظرياً 532 كم/س", "التميز": "أصغر شركة هايبركار في العالم — تصنع يدوياً بالكامل" } },
    { "id": "ca37", "answer": "بورشه كايين", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/2019_Porsche_Cayenne_S_Coup%C3%A9_%28cropped%29.jpg/400px-2019_Porsche_Cayenne_S_Coup%C3%A9_%28cropped%29.jpg", "info": { "الشركة": "Porsche — ألمانيا", "السنة": "2002 — الآن", "المحرك": "V8 توربو 4.0L (Turbo S)", "القوة": "650 حصان", "التميز": "أنجح SUV رياضية فاخرة — أنقذ شركة بورشه من الإفلاس" } },
    { "id": "ca38", "answer": "هوندا NSX", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Honda-nsx-na1-001.jpg/400px-Honda-nsx-na1-001.jpg", "info": { "الشركة": "Honda — اليابان", "السنة": "1990 (الأصل)، 2016 (الإحياء)", "المحرك": "V6 هجين بيتوربو (الجيل الثاني)", "القوة": "573 حصان", "التميز": "تشكيلها شارك فيه أيرتون سينا — فررناند تغيير فكرة السوبركار اليابانية" } },
    { "id": "ca39", "answer": "دودج فايبر", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Dodge_Viper_SRT_GTS_%28cropped%29.jpg/400px-Dodge_Viper_SRT_GTS_%28cropped%29.jpg", "info": { "الشركة": "Dodge — الولايات المتحدة", "السنة": "1992-2017", "المحرك": "V10 طبيعي 8.4L", "القوة": "645 حصان", "التميز": "أكبر محرك إنتاجي V10 — عدائية مطلقة بلا مساعدات إلكترونية" } },
    { "id": "ca40", "answer": "جيب رانغلر", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/2018_Jeep_Wrangler_Unlimited_Sahara_2.0T.jpg/400px-2018_Jeep_Wrangler_Unlimited_Sahara_2.0T.jpg", "info": { "الشركة": "Jeep — الولايات المتحدة", "السنة": "1986 — الآن", "المحرك": "I4/V6 بنزين أو هجين", "التميز": "الأكثر قدرة على الطرق الوعرة — قدرة عبور استثنائية" } },
    { "id": "ca41", "answer": "فولفو XC90", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/2017_Volvo_XC90_D5_AWD_Inscription%2C_front.jpg/400px-2017_Volvo_XC90_D5_AWD_Inscription%2C_front.jpg", "info": { "الشركة": "Volvo — السويد", "السنة": "2002 — الآن", "المحرك": "I4/I6 توربو أو PHEV", "التميز": "الأكثر أماناً في فئتها — تحمل جائزة أفضل سلامة متعددة" } },
    { "id": "ca42", "answer": "هيونداي فيلوستر N", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/2019_Hyundai_Veloster_N%2C_front_10.17.19.jpg/400px-2019_Hyundai_Veloster_N%2C_front_10.17.19.jpg", "info": { "الشركة": "Hyundai — كوريا الجنوبية", "السنة": "2019", "المحرك": "I4 توربو 2.0L", "القوة": "275 حصان", "التميز": "أفضل hot hatch مقابل سعرها" } },
    { "id": "ca43", "answer": "كيا ستينغر GT", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/2019_Kia_Stinger_GT_%28UK%29%2C_front_8.10.19.jpg/400px-2019_Kia_Stinger_GT_%28UK%29%2C_front_8.10.19.jpg", "info": { "الشركة": "Kia — كوريا الجنوبية", "السنة": "2017", "المحرك": "V6 بيتوربو 3.3L", "القوة": "365 حصان", "التميز": "صدمة للعالم — كيا تتحدى BMW و Audi في فئة Gran Turismo" } },
    { "id": "ca44", "answer": "فيات 500", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/2016_Fiat_500_1.2_Pop_%28UK%29%2C_front_8.jpg/400px-2016_Fiat_500_1.2_Pop_%28UK%29%2C_front_8.jpg", "info": { "الشركة": "Fiat — إيطاليا", "السنة": "1957 (الأصل)، 2007 (الإحياء)", "المحرك": "I4 1.2L / 0.9L TwinAir", "التميز": "أيقونة التصميم الإيطالي الخالدة" } },
    { "id": "ca45", "answer": "سيات ليون", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/2017_SEAT_Leon_SC_%28facelift%2C_red%29%2C_front.jpg/400px-2017_SEAT_Leon_SC_%28facelift%2C_red%29%2C_front.jpg", "info": { "الشركة": "SEAT — إسبانيا", "السنة": "1999 — الآن", "المحرك": "I4 1.4T/1.5T/2.0T TSI", "التميز": "الأكثر مبيعاً في إسبانيا تاريخياً" } },
    { "id": "ca46", "answer": "مرسيدس CLA", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/2020_Mercedes-Benz_CLA_200_AMG_Line_%28UK%29.jpg/400px-2020_Mercedes-Benz_CLA_200_AMG_Line_%28UK%29.jpg", "info": { "الشركة": "Mercedes-Benz — ألمانيا", "السنة": "2013 — الآن", "المحرك": "I4 توربو 1.3L-2.0L", "التميز": "مدخل عالم مرسيدس بأسعار تنافسية ومظهر كوبيه" } },
    { "id": "ca47", "answer": "BMW فئة 3", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/2019_BMW_330i_M_Sport_%28facelift%2C_UK%29.jpg/400px-2019_BMW_330i_M_Sport_%28facelift%2C_UK%29.jpg", "info": { "الشركة": "BMW — ألمانيا", "السنة": "1975 — الآن", "المحرك": "I4/I6 توربو", "التميز": "مقياس الأداء للسيارات السيدان — الأكثر مبيعاً لـ BMW" } },
    { "id": "ca48", "answer": "أودي A4", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/2019_Audi_A4_%28B9%2C_facelift%29%2C_front.jpg/400px-2019_Audi_A4_%28B9%2C_facelift%29%2C_front.jpg", "info": { "الشركة": "Audi — ألمانيا", "السنة": "1994 — الآن", "المحرك": "I4/V6 توربو TFSI", "التميز": "جودة الداخلية الاستثنائية — منافس BMW فئة 3 الأبرز" } },
    { "id": "ca49", "answer": "رينو ميغان RS", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/2016_Renault_Megane_GT_Line%2C_front_7.15.jpg/400px-2016_Renault_Megane_GT_Line%2C_front_7.15.jpg", "info": { "الشركة": "Renault — فرنسا", "السنة": "2004 — الآن", "المحرك": "I4 توربو 1.8T-2.0T", "التميز": "ملكة حلبة Nürburgring لفئة hot hatch لسنوات" } },
    { "id": "ca50", "answer": "فولكسفاغن غولف GTI", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Volkswagen_Golf_VII_Facelift_%28cropped%29.jpg/400px-Volkswagen_Golf_VII_Facelift_%28cropped%29.jpg", "info": { "الشركة": "Volkswagen — ألمانيا", "السنة": "1976 — الآن", "المحرك": "I4 توربو TSI 2.0L", "القوة": "245 حصان", "التميز": "مخترع فئة الـ Hot Hatch — المعيار الذي يُقاس عليه الجميع" } }
  ],

  // ══════════════════════════════════════════════
  //  GAME_CHARS — ألعاب (50) — بوسترات بأسماء إنجليزية
  // ══════════════════════════════════════════════
  "game_chars": [
    { "id": "gc01", "answer": "Super Mario Bros", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a9/MarioNSMBUDeluxe.png/400px-MarioNSMBUDeluxe.png", "info": { "المطور": "Nintendo — اليابان", "السنة": "1985", "النوع": "منصات (Platformer)", "المبيعات": "+800 مليون نسخة عبر السلسلة", "التميز": "أشهر سلسلة ألعاب في التاريخ" } },
    { "id": "gc02", "answer": "Pokémon", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/4/43/Pikachu_art.png/400px-Pikachu_art.png", "info": { "المطور": "Game Freak / Nintendo — اليابان", "السنة": "1996", "النوع": "RPG / اصطياد المخلوقات", "المبيعات": "+440 مليون نسخة — ثاني أكبر سلسلة ألعاب", "التميز": "بيكاتشو أيقونة الثقافة الشعبية العالمية" } },
    { "id": "gc03", "answer": "Sonic the Hedgehog", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Sonic_the_Hedgehog_logo.svg/400px-Sonic_the_Hedgehog_logo.svg.png", "info": { "المطور": "SEGA — اليابان", "السنة": "1991", "النوع": "منصات بسرعة عالية", "المبيعات": "+160 مليون نسخة", "التميز": "أيقونة SEGA ومنافس ماريو التاريخي" } },
    { "id": "gc04", "answer": "The Legend of Zelda", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/The_Legend_of_Zelda_Breath_of_the_Wild.jpg/400px-The_Legend_of_Zelda_Breath_of_the_Wild.jpg", "info": { "المطور": "Nintendo — اليابان", "السنة": "1986", "النوع": "مغامرة وأكشن RPG", "المبيعات": "+130 مليون نسخة عبر السلسلة", "التميز": "Breath of the Wild غيّر قواعد العالم المفتوح" } },
    { "id": "gc05", "answer": "Tomb Raider", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a9/Tomb_Raider_%282013%29.jpg/400px-Tomb_Raider_%282013%29.jpg", "info": { "المطور": "Crystal Dynamics / Eidos — المملكة المتحدة", "السنة": "1996", "النوع": "مغامرة وأكشن", "المبيعات": "+88 مليون نسخة", "التميز": "أطلق مفهوم بطلة الألعاب — تحولت لأفلام مع أنجلينا جولي" } },
    { "id": "gc06", "answer": "God of War", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/God_of_War_2018_coverart.png/400px-God_of_War_2018_coverart.png", "info": { "المطور": "Santa Monica Studio — الولايات المتحدة", "السنة": "2005", "النوع": "أكشن مغامرة", "الجوائز": "GOTY 2018 — أكثر من 200 جائزة", "التميز": "قصة أبوة استثنائية في عالم الأساطير الإسكندنافية" } },
    { "id": "gc07", "answer": "Halo: Combat Evolved", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Halo_3_Master_Chief.jpg/400px-Halo_3_Master_Chief.jpg", "info": { "المطور": "Bungie / 343 Industries — الولايات المتحدة", "السنة": "2001", "النوع": "FPS خيال علمي", "المبيعات": "+81 مليون نسخة عبر السلسلة", "التميز": "أطلق نجاح Xbox الأول — أيقونة الـ FPS الكونسول" } },
    { "id": "gc08", "answer": "Marvel's Spider-Man", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Marvel%27s_Spider-Man_cover.jpg/400px-Marvel%27s_Spider-Man_cover.jpg", "info": { "المطور": "Insomniac Games — الولايات المتحدة", "السنة": "2018", "النوع": "أكشن مغامرة عالم مفتوح", "المبيعات": "+33 مليون نسخة", "التميز": "أفضل لعبة أبطال خارقين على الإطلاق" } },
    { "id": "gc09", "answer": "Red Dead Redemption 2", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Red_Dead_Redemption_2.jpg/400px-Red_Dead_Redemption_2.jpg", "info": { "المطور": "Rockstar Games — الولايات المتحدة", "السنة": "2018", "النوع": "مغامرة عالم مفتوح", "المبيعات": "+61 مليون نسخة", "التميز": "أضخم إنتاج في تاريخ الألعاب — 8 سنوات تطوير" } },
    { "id": "gc10", "answer": "The Witcher 3: Wild Hunt", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/The_Witcher_3_cover_art.jpg/400px-The_Witcher_3_cover_art.jpg", "info": { "المطور": "CD Projekt Red — بولندا", "السنة": "2015", "النوع": "RPG عالم مفتوح", "الجوائز": "GOTY 2015 — 200+ جائزة", "التميز": "أفضل RPG في تاريخ الألعاب وفق كثير من المراجعين" } },
    { "id": "gc11", "answer": "Cyberpunk 2077", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Cyberpunk_2077_box_art.jpg/400px-Cyberpunk_2077_box_art.jpg", "info": { "المطور": "CD Projekt Red — بولندا", "السنة": "2020", "النوع": "RPG فضائي عالم مفتوح", "المبيعات": "+25 مليون نسخة", "التميز": "الأكثر انتظاراً في التاريخ — تعافى ليصبح من الأفضل" } },
    { "id": "gc12", "answer": "The Last of Us", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/The_Last_of_Us_cover.jpg/400px-The_Last_of_Us_cover.jpg", "info": { "المطور": "Naughty Dog — الولايات المتحدة", "السنة": "2013", "النوع": "بقاء ورعب وأكشن", "الجوائز": "GOTY 2013 — أكثر من 200 جائزة", "التميز": "تحولت لمسلسل HBO ناجح 2023" } },
    { "id": "gc13", "answer": "Uncharted 4", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Uncharted_4_A_Thief%27s_End.png/400px-Uncharted_4_A_Thief%27s_End.png", "info": { "المطور": "Naughty Dog — الولايات المتحدة", "السنة": "2016", "النوع": "مغامرة أكشن", "المبيعات": "+15 مليون نسخة", "التميز": "تحولت لفيلم 2022 مع توم هولاند" } },
    { "id": "gc14", "answer": "Donkey Kong", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Donkey_Kong_character_art_-_Donkey_Kong_Country_Returns.png/400px-Donkey_Kong_character_art_-_Donkey_Kong_Country_Returns.png", "info": { "المطور": "Nintendo — اليابان", "السنة": "1981", "النوع": "منصات", "التميز": "أول ظهور لماريو في التاريخ كان في مواجهة DK", "المبيعات": "+65 مليون نسخة عبر السلسلة" } },
    { "id": "gc15", "answer": "Pac-Man", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Pac-man_0.png/400px-Pac-man_0.png", "info": { "المطور": "Namco — اليابان", "السنة": "1980", "النوع": "أركيد متاهة", "المبيعات": "+14 مليون نسخة أركيد + مئات الملايين رقمياً", "التميز": "أكثر لعبة أركيد نجاحاً في التاريخ — أيقونة ثقافية" } },
    { "id": "gc16", "answer": "Street Fighter II", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Street_Fighter_Logo.png/400px-Street_Fighter_Logo.png", "info": { "المطور": "Capcom — اليابان", "السنة": "1991", "النوع": "قتال", "المبيعات": "+49 مليون نسخة عبر السلسلة", "التميز": "أسس نوع ألعاب القتال الحديثة — Hadouken أيقوني" } },
    { "id": "gc17", "answer": "Mortal Kombat", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Mortal_Kombat_logo.png/400px-Mortal_Kombat_logo.png", "info": { "المطور": "NetherRealm Studios — الولايات المتحدة", "السنة": "1992", "النوع": "قتال", "التميز": "العنف المبالغ فيه أدى لإنشاء نظام ESRB لتصنيف الألعاب", "المبيعات": "+73 مليون نسخة عبر السلسلة" } },
    { "id": "gc18", "answer": "Minecraft", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Steve_Minecraft.png/400px-Steve_Minecraft.png", "info": { "المطور": "Mojang / Microsoft — السويد", "السنة": "2011", "النوع": "بناء وبقاء مفتوح", "المبيعات": "+300 مليون نسخة — الأول في التاريخ", "التميز": "بدأه شخص واحد في وقت فراغه" } },
    { "id": "gc19", "answer": "Grand Theft Auto V", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Grand_Theft_Auto_V_logo.svg/400px-Grand_Theft_Auto_V_logo.svg.png", "info": { "المطور": "Rockstar Games — الولايات المتحدة", "السنة": "2013", "النوع": "جريمة عالم مفتوح", "المبيعات": "+195 مليون نسخة — ثاني أعلى مبيعاً في التاريخ", "التميز": "حقق مليار دولار في 3 أيام — رقم قياسي ترفيه" } },
    { "id": "gc20", "answer": "Fortnite", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Fortnite_-_Calamity.png/400px-Fortnite_-_Calamity.png", "info": { "المطور": "Epic Games — الولايات المتحدة", "السنة": "2017", "النوع": "Battle Royale / بناء", "اللاعبون": "+350 مليون مسجّل", "التميز": "أطلق موجة Battle Royale وغيّر نموذج Free-to-Play" } },
    { "id": "gc21", "answer": "Overwatch", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Overwatch_logo.svg/400px-Overwatch_logo.svg.png", "info": { "المطور": "Blizzard Entertainment — الولايات المتحدة", "السنة": "2016", "النوع": "FPS تعاوني Hero Shooter", "المبيعات": "+50 مليون نسخة", "التميز": "أسس نوع Hero Shooter وشكّل ثقافة e-sports" } },
    { "id": "gc22", "answer": "League of Legends", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/League_of_Legends_logo_2019.png/400px-League_of_Legends_logo_2019.png", "info": { "المطور": "Riot Games — الولايات المتحدة", "السنة": "2009", "النوع": "MOBA", "اللاعبون": "+150 مليون مسجّل", "التميز": "أكثر ألعاب PC شيوعاً لسنوات — بطولته العالمية تتجاوز مشاهدة Super Bowl" } },
    { "id": "gc23", "answer": "Valorant", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Valorant_logo_-_red_and_white.svg/400px-Valorant_logo_-_red_and_white.svg.png", "info": { "المطور": "Riot Games — الولايات المتحدة", "السنة": "2020", "النوع": "Tactical FPS", "اللاعبون": "+26 مليون شهرياً", "التميز": "أسرع لعبة تاكتيكية نمواً في تاريخ e-sports" } },
    { "id": "gc24", "answer": "PUBG: Battlegrounds", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/PUBG_Logo.svg/400px-PUBG_Logo.svg.png", "info": { "المطور": "Krafton — كوريا الجنوبية", "السنة": "2017", "النوع": "Battle Royale", "المبيعات": "+75 مليون نسخة", "التميز": "رائد نوع Battle Royale — ألهمت Fortnite وكل من بعدها" } },
    { "id": "gc25", "answer": "Call of Duty: Modern Warfare", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Call_of_Duty_Logo.svg/400px-Call_of_Duty_Logo.svg.png", "info": { "المطور": "Activision — الولايات المتحدة", "السنة": "2003 (أول إصدار)", "النوع": "FPS حرب", "المبيعات": "+400 مليون نسخة عبر السلسلة", "التميز": "أكبر سلسلة FPS في التاريخ — Modern Warfare 2007 نقطة تحول" } },
    { "id": "gc26", "answer": "Apex Legends", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Apex_legends_cover.jpg/400px-Apex_legends_cover.jpg", "info": { "المطور": "Respawn Entertainment — الولايات المتحدة", "السنة": "2019", "النوع": "Battle Royale Hero Shooter", "اللاعبون": "+130 مليون مسجّل", "التميز": "مليون لاعب في أول 8 ساعات — رقم قياسي" } },
    { "id": "gc27", "answer": "Dota 2", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Dota_2_logo.png/400px-Dota_2_logo.png", "info": { "المطور": "Valve — الولايات المتحدة", "السنة": "2013", "النوع": "MOBA", "جائزة The International": "+40 مليون دولار — الأضخم في e-sports", "التميز": "أصعب ألعاب MOBA — أعمق نظام تكتيكي" } },
    { "id": "gc28", "answer": "The Elder Scrolls V: Skyrim", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/The_Elder_Scrolls_V_Skyrim_cover.png/400px-The_Elder_Scrolls_V_Skyrim_cover.png", "info": { "المطور": "Bethesda — الولايات المتحدة", "السنة": "2011", "النوع": "RPG عالم مفتوح", "المبيعات": "+60 مليون نسخة", "التميز": "صدرت على 8 منصات — ظاهرة ثقافية لا تنتهي" } },
    { "id": "gc29", "answer": "Fallout 4", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Fallout_4_cover_art.jpg/400px-Fallout_4_cover_art.jpg", "info": { "المطور": "Bethesda — الولايات المتحدة", "السنة": "2015", "النوع": "RPG ما بعد الكارثة", "المبيعات": "+15 مليون نسخة", "التميز": "نظام بناء المستوطنات ثوري — عالم واسع بلا نهاية" } },
    { "id": "gc30", "answer": "Sekiro: Shadows Die Twice", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Sekiro_-_cover_art.jpg/400px-Sekiro_-_cover_art.jpg", "info": { "المطور": "FromSoftware — اليابان", "السنة": "2019", "النوع": "أكشن سمراي", "الجوائز": "GOTY 2019", "التميز": "نظام حركة وقتال يُعدّ الأدق في تاريخ الألعاب" } },
    { "id": "gc31", "answer": "Dark Souls", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Dark_Souls_cover_art.jpg/400px-Dark_Souls_cover_art.jpg", "info": { "المطور": "FromSoftware — اليابان", "السنة": "2011", "النوع": "RPG أكشن صعب", "المبيعات": "+27 مليون نسخة عبر السلسلة", "التميز": "أسس نوع Soulslike — Prepare to Die شعار جيل" } },
    { "id": "gc32", "answer": "Bloodborne", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Bloodborne_cover_art.jpg/400px-Bloodborne_cover_art.jpg", "info": { "المطور": "FromSoftware — اليابان", "السنة": "2015", "النوع": "أكشن RPG رعب", "المبيعات": "+5 مليون نسخة", "التميز": "حصري PS4 — من أفضل 5 ألعاب في تاريخ الجيل الثامن" } },
    { "id": "gc33", "answer": "Horizon Zero Dawn", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Horizon_Zero_Dawn_cover_art.jpg/400px-Horizon_Zero_Dawn_cover_art.jpg", "info": { "المطور": "Guerrilla Games — هولندا", "السنة": "2017", "النوع": "RPG عالم مفتوح", "المبيعات": "+20 مليون نسخة", "التميز": "أفضل IP جديد 2017 — عالم فريد آلات ديناصورية" } },
    { "id": "gc34", "answer": "Mass Effect 2", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Mass_Effect_cover_art.jpg/400px-Mass_Effect_cover_art.jpg", "info": { "المطور": "BioWare — كندا", "السنة": "2010", "النوع": "RPG خيال علمي", "الجوائز": "GOTY 2010 — أفضل لعبة Xbox 360 وفق كثيرين", "التميز": "قراراتك في الجزء الأول تؤثر على نهايات الجزء الثالث" } },
    { "id": "gc35", "answer": "Batman: Arkham City", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Batman_Arkham_City_cover.jpg/400px-Batman_Arkham_City_cover.jpg", "info": { "المطور": "Rocksteady Studios — المملكة المتحدة", "السنة": "2011", "النوع": "أكشن مغامرة عالم مفتوح", "الجوائز": "GOTY 2011 — أفضل لعبة أبطال خارقين", "التميز": "أسس معيار ألعاب الأبطال الخارقين" } },
    { "id": "gc36", "answer": "Assassin's Creed IV: Black Flag", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Assassin%27s_Creed_IV_Black_Flag_cover.jpg/400px-Assassin%27s_Creed_IV_Black_Flag_cover.jpg", "info": { "المطور": "Ubisoft — فرنسا", "السنة": "2013", "النوع": "مغامرة تاريخية مفتوحة", "المبيعات": "+200 مليون عبر السلسلة", "التميز": "تصوير التاريخ بدقة — من القدس لليابان لأثينا" } },
    { "id": "gc37", "answer": "Death Stranding", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Death_Stranding_logo.png/400px-Death_Stranding_logo.png", "info": { "المطور": "Kojima Productions — اليابان", "السنة": "2019", "النوع": "مغامرة فلسفية", "المصمم": "هيديو كوجيما — مبتكر Metal Gear Solid", "التميز": "لعبة عن الوحدة والتواصل — تجربة فريدة لا مثيل لها" } },
    { "id": "gc38", "answer": "Dragon Age: Origins", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Dragon_Age-_Origins_cover_art.jpg/400px-Dragon_Age-_Origins_cover_art.jpg", "info": { "المطور": "BioWare — كندا", "السنة": "2009", "النوع": "RPG فانتازيا تكتيكي", "الجوائز": "GOTY 2009", "التميز": "أعمق نظام قرارات أخلاقية في تاريخ RPG" } },
    { "id": "gc39", "answer": "World of Warcraft", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/World_of_Warcraft_Classic_logo.png/400px-World_of_Warcraft_Classic_logo.png", "info": { "المطور": "Blizzard Entertainment — الولايات المتحدة", "السنة": "2004", "النوع": "MMORPG", "ذروة اللاعبين": "+12 مليون مشترك في آن", "التميز": "شكّل ثقافة الإنترنت — أعظم MMORPG في التاريخ" } },
    { "id": "gc40", "answer": "Among Us", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Among_Us_cover_art.jpg/400px-Among_Us_cover_art.jpg", "info": { "المطور": "InnerSloth — الولايات المتحدة", "السنة": "2018 (شهرة 2020)", "النوع": "خداع اجتماعي", "اللاعبون": "+500 مليون لاعب", "التميز": "صنعه 3 أشخاص فقط — ظاهرة ثقافية 2020" } },
    { "id": "gc41", "answer": "Halo Infinite", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Halo_Infinite_cover_art.png/400px-Halo_Infinite_cover_art.png", "info": { "المطور": "343 Industries — الولايات المتحدة", "السنة": "2021", "النوع": "FPS خيال علمي", "النوع المتعدد": "مجاني Free-to-Play للون لاين", "التميز": "عاد بـ Master Chief بعد 6 سنوات — أعاد الحماس لـ Xbox" } },
    { "id": "gc42", "answer": "Kirby's Dream Land", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Kirby_logo.png/400px-Kirby_logo.png", "info": { "المطور": "HAL Laboratory / Nintendo — اليابان", "السنة": "1992", "النوع": "منصات", "المبيعات": "+50 مليون عبر السلسلة", "التميز": "يبتلع الأعداء ويسرق قدراتهم — أيقونة مرحة لكل الأعمار" } },
    { "id": "gc43", "answer": "Pokémon Red & Blue", "url": "https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Pokemon_red_and_blue_box_art.png/400px-Pokemon_red_and_blue_box_art.png", "info": { "المطور": "Game Freak / Nintendo — اليابان", "السنة": "1996", "النوع": "RPG جيب", "المبيعات": "+31 مليون نسخة للجزء الأول وحده", "التميز": "الجزء الذي أطلق ظاهرة Pokémon العالمية" } },
    { "id": "gc44", "answer": "Spyro Reignited Trilogy", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Spyro_Reignited_Trilogy_logo.svg/400px-Spyro_Reignited_Trilogy_logo.svg.png", "info": { "المطور": "Insomniac Games / Toys for Bob — الولايات المتحدة", "السنة": "1998 (أصل) / 2018 (ريمستر)", "النوع": "منصات مغامرة", "المبيعات": "+10 مليون نسخة للثلاثية", "التميز": "أيقونة PS1 مع بانديكوت وكراش" } },
    { "id": "gc45", "answer": "Crash Bandicoot N. Sane Trilogy", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Crash_Bandicoot_-_The_Wrath_of_Cortex.jpg/400px-Crash_Bandicoot_-_The_Wrath_of_Cortex.jpg", "info": { "المطور": "Naughty Dog / Vicarious Visions", "السنة": "1996 (أصل) / 2017 (ريمستر)", "النوع": "منصات", "المبيعات": "+10 مليون نسخة للريمستر", "التميز": "ماريو الـ PlayStation — أيقونة التسعينيات" } },
    { "id": "gc46", "answer": "Luigi's Mansion", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Luigi_NSMBU2.png/400px-Luigi_NSMBU2.png", "info": { "المطور": "Nintendo — اليابان", "السنة": "2001", "النوع": "مغامرة وأكشن", "المبيعات": "+3.6 مليون نسخة للجزء الأول", "التميز": "بطل أخيراً بعد ظل ماريو سنوات — 2013 عام لويجي" } },
    { "id": "gc47", "answer": "Battlefield 2042", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Battlefield_2042.jpg/400px-Battlefield_2042.jpg", "info": { "المطور": "EA DICE — السويد", "السنة": "2021", "النوع": "FPS حرب", "المبيعات": "+200 مليون عبر السلسلة منذ 2002", "التميز": "المنافس التاريخي لـ COD — مركبات وخرائط ضخمة" } },
    { "id": "gc48", "answer": "Five Nights at Freddy's", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/FNAF_SL_logo.png/400px-FNAF_SL_logo.png", "info": { "المطور": "Scott Cawthon — الولايات المتحدة", "السنة": "2014", "النوع": "رعب بقاء", "التميز": "صنعه شخص واحد — نما لفرانشايز ضخم وأفلام سينمائية", "السبب": "رعب الانتظار والخوف من اللحظة أكثر من الصورة" } },
    { "id": "gc49", "answer": "Roblox", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Roblox_logo.png/400px-Roblox_logo.png", "info": { "المطور": "Roblox Corporation — الولايات المتحدة", "السنة": "2006", "النوع": "منصة ألعاب مجتمعية", "اللاعبون": "+200 مليون شهرياً", "التميز": "اللاعبون هم المطورون — الأشهر لدى الأطفال دون 13 عالمياً" } },
    { "id": "gc50", "answer": "Terraria", "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Terraria_Logo.png/400px-Terraria_Logo.png", "info": { "المطور": "Re-Logic — الولايات المتحدة", "السنة": "2011", "النوع": "مغامرة وبناء 2D", "المبيعات": "+44 مليون نسخة", "التميز": "صنعه شخصان فقط — يُلقّب بـ Minecraft ثنائي الأبعاد" } }
  ]

};

// ══════════════════════════════════════════════════════════════
//  GUESS_CATEGORIES — قائمة الفئات
// ══════════════════════════════════════════════════════════════
export const GUESS_CATEGORIES = [
  { id: 'athletes',   emoji: '⚽', nameAr: 'رياضيون'       },
  { id: 'countries',  emoji: '🌍', nameAr: 'دول'            },
  { id: 'animals',    emoji: '🐾', nameAr: 'حيوانات'        },
  { id: 'food',       emoji: '🍕', nameAr: 'أكل'            },
  { id: 'actors',     emoji: '🎬', nameAr: 'ممثلون'         },
  { id: 'arab_stars', emoji: '🌟', nameAr: 'نجوم عرب'      },
  { id: 'movies',     emoji: '🎥', nameAr: 'أفلام'          },
  { id: 'jobs',       emoji: '💼', nameAr: 'مهن'            },
  { id: 'film_chars', emoji: '🦸', nameAr: 'شخصيات أفلام'  },
  { id: 'cars',       emoji: '🚗', nameAr: 'سيارات'         },
  { id: 'game_chars', emoji: '🎮', nameAr: 'ألعاب'           },
  { id: 'things',     emoji: '🔧', nameAr: 'أشياء'          },
];

// ══════════════════════════════════════════════════════════════
//  pickRandomImage — اختيار صورة عشوائية مع تجنب المكررة
// ══════════════════════════════════════════════════════════════
/**
 * @param {string}   catId    — معرّف الفئة
 * @param {string[]} usedIds  — معرّفات الصور المستخدمة مسبقاً
 * @returns {{ id, answer, url, info? } | null}
 */
export function pickRandomImage(catId, usedIds = []) {
  const pool = GUESS_IMAGE_DATA[catId];
  if (!pool || pool.length === 0) return null;
  const available = pool.filter(img => !usedIds.includes(img.id));
  const source = available.length > 0 ? available : pool;
  return source[Math.floor(Math.random() * source.length)];
}
